- name: run drone server
  docker_container:
    name: drone-server
    image: "drone/drone:{{drone_version}}"
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
      - "9000:9000"
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - /drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - postgres
    env:
      DRONE_SERVER_HOST: "{{drone_server_host}}"
      DRONE_SERVER_ADDR: ":8000"
      DRONE_LOGS_DEBUG: "true"
      DRONE_RPC_SECRET: "{{drone_rpc_secret}}"
      DRONE_DATABASE_DRIVER: postgres
      DRONE_DATABASE_DATASOURCE: postgres://{{drone_postgress_user}}:{{drone_postgress_password}}@postgres:5432/{{drone_postgress_db}}?sslmode=disable
      DRONE_USER_CREATE: "{{drone_user_create}}"
      DRONE_GITHUB_CLIENT_ID: "{{drone_github_client_id}}"
      DRONE_GITHUB_CLIENT_SECRET: "{{drone_github_client_secret}}"
      DRONE_GITHUB_SKIP_VERIFY: "true"
      DRONE_GITEA_SERVER: "{{drone_gitea_server_host}}"
      DRONE_GITEA_CLIENT_ID: "{{drone_gitea_client_id}}"
      DRONE_GITEA_CLIENT_SECRET: "{{drone_gitea_client_secret}}"
  tags:
    - drone
    - server

- name: run drone agent
  docker_container:
    name: "agent-{{item.name}}"
    image: "drone/agent:{{drone_version}}"
    privileged: yes
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - drone-server
    env:
      DRONE_RPC_SERVER: "drone-server:9000"
      DRONE_RPC_SECRET: "{{drone_rpc_secret}}"
      DRONE_LOGS_DEBUG: "true"
  with_items: "{{drone_agents}}"
  tags:
    - drone
    - agent
